
package client.com.guidewire.mobility.webservices.iloginwrapperapi.service.iloginwrapperapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import client.com.guidewire.mobility.webservices.iloginwrapperapi.vo.loginrequest.LoginRequest;
import client.com.guidewire.mobility.webservices.iloginwrapperapi.vo.loginresponse.LoginResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ILoginWrapperAPIPortType", targetNamespace = "http://guidewire.com/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI")
@XmlSeeAlso({
	client.com.guidewire.mobility.webservices.iloginwrapperapi.service.iloginwrapperapi.ObjectFactory.class,
	client.com.guidewire.ws.soapheaders.ObjectFactory.class,
	client.com.guidewire.mobility.webservices.iloginwrapperapi.vo.loginresponse.ObjectFactory.class,
	client.com.guidewire.mobility.webservices.iloginwrapperapi.vo.loginrequest.ObjectFactory.class
})
public interface ILoginWrapperAPIPortType {


    /**
     * 
     * @param loginRequest
     * @return
     *     returns com.guidewire.mobility.webservices.iloginwrapperapi.vo.loginresponse.LoginResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "http://guidewire.com/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI")
    @RequestWrapper(localName = "login", targetNamespace = "http://guidewire.com/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI", className = "com.guidewire.mobility.webservices.iloginwrapperapi.service.iloginwrapperapi.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://guidewire.com/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI", className = "com.guidewire.mobility.webservices.iloginwrapperapi.service.iloginwrapperapi.LoginResponse")
    public LoginResponse login(
        @WebParam(name = "loginRequest", targetNamespace = "http://guidewire.com/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI")
        LoginRequest loginRequest);

}
