
package client.com.guidewire.mobility.webservices.iloginwrapperapi.service.iloginwrapperapi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ILoginWrapperAPI", targetNamespace = "http://guidewire.com/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI", wsdlLocation = "http://usblrvakamat7:8580/bc/ws/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI?WSDL")
public class ILoginWrapperAPI
    extends Service
{

    private final static URL ILOGINWRAPPERAPI_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(client.com.guidewire.mobility.webservices.iloginwrapperapi.service.iloginwrapperapi.ILoginWrapperAPI.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = client.com.guidewire.mobility.webservices.iloginwrapperapi.service.iloginwrapperapi.ILoginWrapperAPI.class.getResource(".");
            url = new URL(baseUrl, "http://usblrvakamat7:8580/bc/ws/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://usblrvakamat7:8580/bc/ws/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ILOGINWRAPPERAPI_WSDL_LOCATION = url;
    }

    public ILoginWrapperAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ILoginWrapperAPI() {
        super(ILOGINWRAPPERAPI_WSDL_LOCATION, new QName("http://guidewire.com/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI", "ILoginWrapperAPI"));
    }

    /**
     * 
     * @return
     *     returns ILoginWrapperAPIPortType
     */
    @WebEndpoint(name = "ILoginWrapperAPISoap11Port")
    public ILoginWrapperAPIPortType getILoginWrapperAPISoap11Port() {
        return super.getPort(new QName("http://guidewire.com/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI", "ILoginWrapperAPISoap11Port"), ILoginWrapperAPIPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILoginWrapperAPIPortType
     */
    @WebEndpoint(name = "ILoginWrapperAPISoap11Port")
    public ILoginWrapperAPIPortType getILoginWrapperAPISoap11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://guidewire.com/mobility/webservices/ILoginWrapperAPI/service/ILoginWrapperAPI", "ILoginWrapperAPISoap11Port"), ILoginWrapperAPIPortType.class, features);
    }

}
