
package service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This is a simple web - service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GreetService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GreetService {


    /**
     * 
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service/", className = "service.client.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service/", className = "service.client.SayHiResponse")
    public String sayHi(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param doc
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadDoc", targetNamespace = "http://service/", className = "service.client.UploadDoc")
    @ResponseWrapper(localName = "uploadDocResponse", targetNamespace = "http://service/", className = "service.client.UploadDocResponse")
    public String uploadDoc(
        @WebParam(name = "doc", targetNamespace = "")
        byte[] doc);

}
