
package service.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GreetService", targetNamespace = "http://www.springframework.org/schema/beans", wsdlLocation = "http://localhost:8080/Java_WS_Spring2/services/greetservice?wsdl")
public class GreetService_Service
    extends Service
{

    private final static URL GREETSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(service.client.GreetService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = service.client.GreetService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/Java_WS_Spring2/services/greetservice?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/Java_WS_Spring2/services/greetservice?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GREETSERVICE_WSDL_LOCATION = url;
    }

    public GreetService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GreetService_Service() {
        super(GREETSERVICE_WSDL_LOCATION, new QName("http://www.springframework.org/schema/beans", "GreetService"));
    }

    /**
     * 
     * @return
     *     returns GreetService
     */
    @WebEndpoint(name = "GreetServiceImplPort")
    public GreetService getGreetServiceImplPort() {
        return super.getPort(new QName("http://www.springframework.org/schema/beans", "GreetServiceImplPort"), GreetService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GreetService
     */
    @WebEndpoint(name = "GreetServiceImplPort")
    public GreetService getGreetServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.springframework.org/schema/beans", "GreetServiceImplPort"), GreetService.class, features);
    }

}
